spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classroom?createDatabaseIfNotExist=true
    username: root
    password: root1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8011
