spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classroom?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      add-mappings: true
server:
  port: 8011
