spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classroom?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8011
project:
  image: files/images
  file: files/content